logging:
  level:

    org.springframework.web.multipart: INFO
    org.springframework.web.servlet.resource: INFO
    org.springframework.security: INFO

    com.zaxxer.hikari: INFO
    org.hibernate.SQL: INFO