spring:
  datasource:
    jdbc-url: jdbc:mariadb://185.176.94.192:3306/s17_Kai_test?useSSL=false&serverTimezone=UTC
    username: u17_NfY7Mgd1wV
    password: lHoiXHoTCNWXPCdIUo!u^^Kt
    driver-class-name: org.mariadb.jdbc.Driver

    connection-timeout: 30000
    minimum-idle: 2
    maximum-pool-size: 10
    idle-timeout: 600000
    max-lifetime: 1800000
    leak-detection-threshold: 30000
    validation-timeout: 5000
    keepalive-time: 300000