logging:
  level:

    org.springframework.web.multipart: INFO
    org.springframework.web.servlet.resource: INFO
    org.springframework.security: DEBUG

    org.springframework.web.socket: DEBUG
    org.springframework.messaging: INFO

    org.kirya343.core.audio: INFO

    com.zaxxer.hikari: INFO
    org.hibernate.SQL: INFO